name = "Peter"
uuid = "b8bfe48c-c90e-4a16-b2aa-2e3d5f1d3f92"
repo = "https://github.com/peterahrens/Peter.jl"
description = "Peter's Registry"

[packages]
fedcd5e3-25fa-4517-9d96-0ffbee4aa29d = { name = "Tune", path = "T/Tune" }
