name = "Peter"
uuid = "b8bfe48c-c90e-4a16-b2aa-2e3d5f1d3f92"
repo = "https://github.com/peterahrens/Peter.jl"
description = "Peter's Registry"

[packages]
7a2a9441-b812-4af5-b203-314e7cbd5d81 = { name = "ChainPartitioners", path = "C/ChainPartitioners" }
a606033f-14ee-4438-ae87-3b404a2b735d = { name = "DiskBackedDicts", path = "D/DiskBackedDicts" }
fedcd5e3-25fa-4517-9d96-0ffbee4aa29d = { name = "Tune", path = "T/Tune" }
